CREATE DATABASE MUTANTDB;

CREATE TABLE IF NOT EXISTS `MUTANTDB.MUTANTS`  (
    MUTANT_ID INT NOT NULL AUTO_INCREMENT,
    MUTANT_DNA_SECUENCE tinyblob NOT NULL,
    MUTANT_STATUS BIT(1) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (MUTANT_ID)
);